### ISSUE TITLE
Font appears small for first time

### ISSUE THREAD

**Issue by miskinmaz** [ClimberAB/ClimberKPI#27] opened 2019-01-08 07:46 UTC
### Versions
* Extension version: 1.6.0
* Qlik Sense:  Nov 18
* Browser:  Chrome

### Description
When you open the app for the first time with no selection, then all fonts are appearing small

### Steps to Reproduce

1. Open the app, for the first time, and observe the kpi.
2. If any selection is made after that then the font appears in original form. Refreshing the browser also helps the same.

##### Expected behavior
Font size should be same throughout.

Thanks and Regards
Miskin

**Comment by stevefewster** [comment] 2019-01-08 10:48
We are also experiencing this issue as well. 

I've attached a screen shot of the issue. KPI boxes are not visible , looks like they are half height?, however when moving to the next sheet and returning to this sheet, the KPI display correctly. 

Extension - 1.6
Qliksense - June 2018. 
Browser - Chrome

Thanks
Steve

![kpi fault](https://user-images.githubusercontent.com/4234002/50826110-b3f54900-1332-11e9-8206-a85075a9db8e.png)

**Comment by stevefewster** [comment] 2019-01-08 12:42
It's happening on Enterprise. I've just upgraded to Nov 2018 and it's still there. 

When I press Ctrl Shift J, it resolves the issue as the screen is redrawn. There is a note in the console however which is attached below. 
![kpi fault 1](https://user-images.githubusercontent.com/4234002/50831477-d8592180-1342-11e9-9026-6c8ba695616c.png)

Cheers
Steve

**Comment by kfsjostrand** [comment] 2019-01-08 14:50
I manage to recreate it, and it was caused by some css issues when removing the thick header in focus theme.
Check out the latest release and the issue should be fixed. 
Download it here:
https://github.com/ClimberAB/ClimberKPI/releases/tag/v1.6.1

**Closed by kfsjostrand** 2019-01-08 14:50 UTC
